use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=src/plugin.c");
    println!("cargo:rerun-if-changed=src/suricata-compat.h");
    println!("cargo:rerun-if-env-changed=DEP_NDPI_INCLUDE");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    fs::write(
        out_dir.join("suricata_8_bindings.rs"),
        suricata_8_bindings(),
    )
    .expect("failed to write Suricata 8 bindings");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let ndpi_include_dir = env::var("DEP_NDPI_INCLUDE")
        .map(PathBuf::from)
        .expect("missing DEP_NDPI_INCLUDE from ndpi-sys");

    let plugin_version = env::var("CARGO_PKG_VERSION").expect("missing CARGO_PKG_VERSION");
    let plugin_version_c = format!("\"{}\"", plugin_version);

    let mut build = cc::Build::new();
    build
        .file(manifest_dir.join("src/plugin.c"))
        .include(&ndpi_include_dir)
        .flag_if_supported("-std=gnu11")
        .flag_if_supported("-Wno-unused-parameter")
        .define("NDPI_PLUGIN_VERSION", Some(plugin_version_c.as_str()));
    build.compile("plugin_shim");

    println!("cargo:rustc-link-lib=static=ndpi");

    if env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() != "windows" {
        println!("cargo:rustc-link-lib=m");
    }
}

fn suricata_8_bindings() -> &'static str {
    r#"// Automatically generated by build.rs. Do not edit.

use core::ffi::{c_char, c_void};

pub const SC_API_VERSION: u64 = 0x0800;
pub const SC_PACKAGE_VERSION: &[u8] = b"8.0.x\0";

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SCPlugin {
    pub version: u64,
    pub suricata_version: *const c_char,
    pub name: *const c_char,
    pub plugin_version: *const c_char,
    pub license: *const c_char,
    pub author: *const c_char,
    pub Init: Option<unsafe extern "C" fn()>,
}

pub type SCPluginRegisterFunc = Option<unsafe extern "C" fn() -> *mut SCPlugin>;

extern "C" {
    pub fn SCPluginRegisterCapture(plugin: *mut c_void) -> i32;
    pub fn SCPluginRegisterAppLayer(plugin: *mut c_void) -> i32;
}
"#
}
